name: Run FPL Bot Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'   # daily at 04:00 UTC

jobs:
  run-bot:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install playwright
          playwright install

      - name: Download NLTK data
        run: python -m nltk.downloader vader_lexicon

      - name: Run FPL bot
        run: python fpl_auto_bot.py
        env:
          FPL_EMAIL: ${{ secrets.FPL_EMAIL }}
          FPL_PASSWORD: ${{ secrets.FPL_PASSWORD }}
          FPL_TEAM_ID: ${{ secrets.FPL_TEAM_ID }}
