name: Run FPL Bot Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 9 AM Pakistan time

jobs:
  run-bot:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run FPL bot
        run: python fpl_auto_bot.py
